version: "3"
services:
  api:
    image: otaviomedeiros/multi-server
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: otaviomedeiros/multi-worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  client:
    image: otaviomedeiros/multi-client
  nginx:
    image: otaviomedeiros/multi-nginx
    ports:
      - 80:80
    depends_on:
      - api
      - client