name: Deploy
on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Test react app
        run: |
          docker build -t otaviomedeiros/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true otaviomedeiros/react-test npm test

      - name: Build docker images
        run: |
          docker build -t otaviomedeiros/multi-client ./client
          docker build -t otaviomedeiros/multi-nginx ./nginx
          docker build -t otaviomedeiros/multi-server ./server
          docker build -t otaviomedeiros/multi-worker ./worker
        
      - name: Push images do Dockerhub
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
          docker push otaviomedeiros/multi-client
          docker push otaviomedeiros/multi-nginx
          docker push otaviomedeiros/multi-server
          docker push otaviomedeiros/multi-worker